/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Data;
import Object.NhanVien;
import Object.PhongBan;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author phung
 */
public class UiFromPhongBan extends javax.swing.JFrame {
    
    private int position = -1  ;
    private DefaultTableModel modelPhongBanTable;
    private int idMax;
    /**
     * Creates new form UiFromPhongBan
     */
    public UiFromPhongBan() {
        initComponents();
        this.modelPhongBanTable = (DefaultTableModel) jTable_BangPhongBan.getModel();
        hienThiDSPhongBan();
    }
    public void hienThiDSPhongBan(){
        if(Data.phongbanList.size()!=0){
        this.idMax = Data.phongbanList.get(0).getMaPhongBan();
        for(PhongBan phongban:Data.phongbanList){
            this.modelPhongBanTable.addRow(new Object[]{
                phongban.getMaPhongBan(),
                phongban.getTenPhongBan()
            });
            if(idMax<phongban.getMaPhongBan()) idMax = phongban.getMaPhongBan();
        }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_MaPhongBan = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_TenPhongBan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_BangPhongBan = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable_BangHienThi = new javax.swing.JTable();
        jButton_ThemPhongBan = new javax.swing.JButton();
        jButton_XoaPhongBan = new javax.swing.JButton();
        jButton_SuaPhongBan = new javax.swing.JButton();
        jButton_nhayQuanNhanVien = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Corbel Light", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản Lí Phòng Ban");

        jLabel2.setText("Mã phòng ban:");

        jLabel3.setText("Tên phòng ban:");

        jTable_BangPhongBan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Phòng Ban", "Tên Phòng Ban"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_BangPhongBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_BangPhongBanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_BangPhongBan);

        jTable_BangHienThi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Nhân Viên", "Tên Nhân Viên", "Giới Tính", "Số CMND", "Lương Cơ Bản", "Ngày Vào Làm", "Số Ngày Làm Việc", "Sở Thích", "Phòng Ban"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_BangHienThi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_BangHienThiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable_BangHienThiMouseEntered(evt);
            }
        });
        jScrollPane5.setViewportView(jTable_BangHienThi);

        jButton_ThemPhongBan.setText("Thêm Phòng Ban");
        jButton_ThemPhongBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThemPhongBanActionPerformed(evt);
            }
        });

        jButton_XoaPhongBan.setText("Xóa Phòng Ban");

        jButton_SuaPhongBan.setText("Sửa Phòng Ban");

        jButton_nhayQuanNhanVien.setText("Nhảy Qua Nhân Viên");
        jButton_nhayQuanNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_nhayQuanNhanVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel_MaPhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_TenPhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_ThemPhongBan)
                                .addGap(3, 3, 3)
                                .addComponent(jButton_XoaPhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_SuaPhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton_nhayQuanNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel_MaPhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField_TenPhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_ThemPhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_XoaPhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_SuaPhongBan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_nhayQuanNhanVien)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable_BangHienThiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_BangHienThiMouseClicked
      
    }//GEN-LAST:event_jTable_BangHienThiMouseClicked

    private void jTable_BangHienThiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_BangHienThiMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable_BangHienThiMouseEntered

    private void jButton_nhayQuanNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_nhayQuanNhanVienActionPerformed
        if(this.position!=-1){
        new UiFormNhanVien(Data.phongbanList.get(this.position).getDsNhanVien(), this.position).setVisible(true);
        }
    }//GEN-LAST:event_jButton_nhayQuanNhanVienActionPerformed

    private void jButton_ThemPhongBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThemPhongBanActionPerformed
        int maPBAdd = idMax + 1;
        String tenPBAdd = jTextField_TenPhongBan.getText();
        DateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        Date today = new Date();
        try {
            Date todayWithZeroTime = formatter.parse(formatter.format(today));
            ArrayList<String> sothichAdd = new ArrayList<>();
            sothichAdd.add("Học");
            sothichAdd.add("kiếm tiền");
             NhanVien nhanvien = new NhanVien(1,"Quân",true,1234,todayWithZeroTime
                     , (float) 10.05,15,sothichAdd,maPBAdd);
             ArrayList<NhanVien> nhanVienList = new ArrayList<>();
             nhanVienList.add(nhanvien);
             PhongBan pb = new PhongBan(maPBAdd, tenPBAdd,nhanVienList);
          Data.phongbanList.add(pb);
          modelPhongBanTable.setRowCount(0);
          hienThiDSPhongBan();
        } catch (ParseException ex) {
            Logger.getLogger(UiFromPhongBan.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_jButton_ThemPhongBanActionPerformed

    private void jTable_BangPhongBanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_BangPhongBanMouseClicked
        this.position = jTable_BangPhongBan.getSelectedRow();
    }//GEN-LAST:event_jTable_BangPhongBanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UiFromPhongBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UiFromPhongBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UiFromPhongBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UiFromPhongBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UiFromPhongBan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_SuaPhongBan;
    private javax.swing.JButton jButton_ThemPhongBan;
    private javax.swing.JButton jButton_XoaPhongBan;
    private javax.swing.JButton jButton_nhayQuanNhanVien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_MaPhongBan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable_BangHienThi;
    private javax.swing.JTable jTable_BangPhongBan;
    private javax.swing.JTextField jTextField_TenPhongBan;
    // End of variables declaration//GEN-END:variables
}
